image: docker:latest

services:
- name: docker:edge-dind
  command: ["--experimental"]

variables:
  REGISTRY_URL: "docker.io"  # other registry URL, DOCKER_REGISTRY_PASSWORD and DOCKER_REGISTRY_USER to be set in CI env.
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --no-cache curl && echo IP=$(curl -s http://ifconfig.me/ip)
  - docker info
  - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
      echo "$DOCKER_REGISTRY_PASSWORD" | docker login "${REGISTRY_URL}" -u "$DOCKER_REGISTRY_USER" --password-stdin
    fi
  
stages:
  - base
  - cuda
  - jpy
  - qpod

.build_tpl: &builder
  before_script:
    - echo "Building Image> ${CI_COMMIT_REF_NAME}:${CI_JOB_NAME}"
    - build_image() { TAG=$1; FILE=$2; shift 2; docker build --force-rm=true -t "${REPOSITORY}:$TAG" -f "$FILE" "$@" "$(dirname $FILE)"; }
    - alias_image() { docker tag "${REPOSITORY}:$1" "${REPOSITORY}:$2"; }
    - CI_PROJECT_NAME="qpod"
    - REPOSITORY=$(echo "${REGISTRY_URL}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}" | awk '{print tolower($0)}')

  after_script:
    - docker image prune --force && docker images
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
          docker push "${REPOSITORY}";
      fi


base:
  <<: *builder
  stage: base
  script:
  - build_image "${CI_JOB_NAME}" "docker_base/Dockerfile"
    --squash


base-cuda_10.1:
  <<: *builder
  stage: cuda
  script:
  - build_image "${CI_JOB_NAME}" "docker_base/Dockerfile-cuda10.1"
    --build-arg "repository=${REPOSITORY}"
    --squash

base-cuda_10.0:
  <<: *builder
  stage: cuda
  script:
  - build_image "${CI_JOB_NAME}" "docker_base/Dockerfile-cuda10.0"
    --build-arg "repository=${REPOSITORY}"
    --squash
  - alias_image "${CI_JOB_NAME}" "cuda"

jupyter-mini:
  <<: *builder
  stage: jpy
  script:
  - build_image "${CI_JOB_NAME}" "docker_jpy/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "ARG_EXTEND_JUPYTER=false"
    --build-arg "ARG_NODEJS=false"
    --build-arg "ARG_LATEX_BASE=false"
    --build-arg "ARG_LATEX_CJK=false"

jupyter-mini-cuda:
  <<: *builder
  stage: jpy
  script:
  - build_image "${CI_JOB_NAME}" "docker_jpy/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "base=cuda"
    --build-arg "ARG_EXTEND_JUPYTER=false"
    --build-arg "ARG_NODEJS=false"
    --build-arg "ARG_LATEX_BASE=false"
    --build-arg "ARG_LATEX_CJK=false"

jupyter-std:
  <<: *builder
  stage: jpy
  script:
  - build_image "${CI_JOB_NAME}" "docker_jpy/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "ARG_EXTEND_JUPYTER=true"
    --build-arg "ARG_NODEJS=true"
    --build-arg "ARG_LATEX_BASE=false"
    --build-arg "ARG_LATEX_CJK=false"

jupyter-full:
  <<: *builder
  stage: jpy
  script:
  - build_image "${CI_JOB_NAME}" "docker_jpy/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "ARG_EXTEND_JUPYTER=true"
    --build-arg "ARG_NODEJS=true"
    --build-arg "ARG_LATEX_BASE=true"
    --build-arg "ARG_LATEX_CJK=true"

jupyter-full-cuda:
  <<: *builder
  stage: jpy
  script:
  - build_image "${CI_JOB_NAME}" "docker_jpy/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "base=cuda"
    --build-arg "ARG_EXTEND_JUPYTER=true"
    --build-arg "ARG_NODEJS=true"
    --build-arg "ARG_LATEX_BASE=true"
    --build-arg "ARG_LATEX_CJK=true"


r-mini:
  <<: *builder
  stage: qpod
  script:
  - build_image "${CI_JOB_NAME}" "docker_template/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "base=jupyter-mini"
    --build-arg "ARG_R=true"

r-std:
  <<: *builder
  stage: qpod
  script:
  - build_image "${CI_JOB_NAME}" "docker_template/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "base=jupyter-std"
    --build-arg "ARG_JDK=true"
    --build-arg "ARG_R=true"
    --build-arg "ARG_R_DATASCIENCE=true"

r-latex:
  <<: *builder
  stage: qpod
  script:
  - build_image "${CI_JOB_NAME}" "docker_template/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "base=jupyter-full"
    --build-arg "ARG_JDK=true"
    --build-arg "ARG_R=true"
    --build-arg "ARG_R_DATASCIENCE=true"
    --build-arg "ARG_LATEX_BASE=true"

r-studio:
  <<: *builder
  stage: qpod
  script:
  - build_image "${CI_JOB_NAME}" "docker_template/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "base=jupyter-full"
    --build-arg "ARG_JDK=true"
    --build-arg "ARG_R=true"
    --build-arg "ARG_R_DATASCIENCE=true"
    --build-arg "ARG_R_STUDIO=true"
    --build-arg "ARG_LATEX_BASE=true"
    --build-arg "ARG_LATEX_CJK=true"


py-std:
  <<: *builder
  stage: qpod
  script:
  - build_image "${CI_JOB_NAME}" "docker_template/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "base=jupyter-std"
    --build-arg "ARG_MKL=true"
    --build-arg "ARG_PY_DATABASE=true"
    --build-arg "ARG_PY_DATASCIENCE=true"
    --build-arg "ARG_PY_NLP=true"
    --build-arg "ARG_PY_CV=true"
    --build-arg "ARG_PY_BIOINFO=true"

py-jdk:
  <<: *builder
  stage: qpod
  script:
  - build_image "${CI_JOB_NAME}" "docker_template/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "base=jupyter-std"
    --build-arg "ARG_JDK=true"
    --build-arg "ARG_MKL=true"
    --build-arg "ARG_PY_DATABASE=true"
    --build-arg "ARG_PY_DATASCIENCE=true"
    --build-arg "ARG_PY_NLP=true"
    --build-arg "ARG_PY_CV=true"
    --build-arg "ARG_PY_BIOINFO=true"

py-cuda:
  <<: *builder
  stage: qpod
  script:
  - build_image "${CI_JOB_NAME}" "docker_template/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "base=jupyter-full-cuda"
    --build-arg "ARG_MKL=true"
    --build-arg "ARG_PY_DATABASE=true"
    --build-arg "ARG_PY_DATASCIENCE=true"
    --build-arg "ARG_PY_NLP=true"
    --build-arg "ARG_PY_CV=true"
    --build-arg "ARG_PY_BIOINFO=true"


go:
  <<: *builder
  stage: qpod
  script:
  - build_image "${CI_JOB_NAME}" "docker_template/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "base=jupyter-std"
    --build-arg "ARG_GO=true"

julia:
  <<: *builder
  stage: qpod
  script:
  - build_image "${CI_JOB_NAME}" "docker_template/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "base=jupyter-std"
    --build-arg "ARG_JULIA=true"

octave:
  <<: *builder
  stage: qpod
  script:
  - build_image "${CI_JOB_NAME}" "docker_template/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "base=jupyter-std"
    --build-arg "ARG_OCTAVE=true"


full:
  <<: *builder
  stage: qpod
  script:
  - build_image "${CI_JOB_NAME}" "docker_template/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "base=jupyter-full"
    --build-arg "ARG_JDK=true"
    --build-arg "ARG_MKL=true"
    --build-arg "ARG_PY_DATABASE=true"
    --build-arg "ARG_PY_DATASCIENCE=true"
    --build-arg "ARG_PY_NLP=true"
    --build-arg "ARG_PY_CV=true"
    --build-arg "ARG_PY_BIOINFO=true"
    --build-arg "ARG_R=true"
    --build-arg "ARG_R_DATASCIENCE=true"
    --build-arg "ARG_R_STUDIO=true"
    --build-arg "ARG_GO=true"
    --build-arg "ARG_JULIA=true"
    --build-arg "ARG_OCTAVE=true"
  - alias_image "${CI_JOB_NAME}" "latest"

full-cuda:
  <<: *builder
  stage: qpod
  script:
  - build_image "${CI_JOB_NAME}" "docker_template/Dockerfile"
    --build-arg "repository=${REPOSITORY}"
    --build-arg "base=jupyter-full-cuda"
    --build-arg "ARG_JDK=true"
    --build-arg "ARG_MKL=true"
    --build-arg "ARG_PY_DATABASE=true"
    --build-arg "ARG_PY_DATASCIENCE=true"
    --build-arg "ARG_PY_NLP=true"
    --build-arg "ARG_PY_CV=true"
    --build-arg "ARG_PY_BIOINFO=true"
    --build-arg "ARG_R=true"
    --build-arg "ARG_R_DATASCIENCE=true"
    --build-arg "ARG_R_STUDIO=true"
    --build-arg "ARG_GO=true"
    --build-arg "ARG_JULIA=true"
    --build-arg "ARG_OCTAVE=true"
  - alias_image "${CI_JOB_NAME}" "latest-cuda"
